version: '3.9'

services:
  app:
    build:
      context: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - elasticsearch
    env_file: 
      - .env 
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
